ls_url = "http://127.0.0.1:4242"
ls_admin_user = "xox"
ls_admin_pass = "laaPhie*aiN0"
web_url = "http://127.0.0.1:8080"
public_ws_url = "ws://127.0.0.1:8081"
internal_ws_port = 10000
shutdown_timeout_ms = 2000
# set it to where your Elfencore.Console is
core_session_project_path = "../elfencore/src/Elfencore.Console"
demo_mode = false
savegames_path = "./savegames/"
built_core_path = "./coreBinary/"
dotnet_binary_name = "Elfencore.Console.dll"
min_token_refresh_s = 60
# gameservice:rounds:dest_town:witch:random_gold
allowed_games = [
    "land:3:true",
    "land:3:false",
    "land:4:true",
    "land:4:false",
    "gold:6:true:true:true",
    "gold:6:true:true:false",
    "gold:6:true:false:true",
    "gold:6:true:false:false",
    "gold:6:false:true:true",
    "gold:6:false:true:false",
    "gold:6:false:false:true",
    "gold:6:false:false:false",
]